### ISSUE TITLE
Prefer 32-bit

### ISSUE THREAD

**Issue by TanukiSharp** [r00telement/SmartHunter#17]
Hi, wonderful work on this tool.

When I run SmartHunter, it fails at boot, the reason is because pointers beyond 32 bits can't be cast from `ulong` to `IntPtr`. The fix is very simple, uncheck the `Prefer 32-bit` option is project settings.

![image](https://user-images.githubusercontent.com/4018313/59558791-609bcb00-9035-11e9-9e7b-f40c6b06beae.png)

Monter Hunter World is built fro 64-bit CPUs anyway so I don't think it makes sense to prefer 32-bit. Is there a reason for that or was it just the default you never changed ?

**Comment by r00telement** [comment]
The project should be built with x64 as the platform target. The only reason I left Any CPU in as a target is because the UI designer can't be used with 64 bit. So if you want to use Blend, build in 32 bit.
