### ISSUE TITLE
Monster parts non-functional.

### ISSUE THREAD

**Issue by sirdoombox** [r00telement/SmartHunter#18]
Currently the monster parts display of the latest available build on NexusMods isn't functional, "ShowUnchangedParts" setting in false seems to only occasionally display parts that have been broken, setting it to true however has nothing shown at all.

My config file is entirely stock and untouched apart from the X/Y positions of the widgets.

Quick edit: seems to only completely break in multiplayer, functions fine in singleplayer. Rarely ever play solo so I didn't notice.

**Comment by r00telement** [comment]
On the Nexus page, there's a note that monster parts only update properly in multiplayer if you are the host. Not a bug, just how the game works, and we can't work around it unfortunately.
