### ISSUE TITLE
ShowUnchanged true not quite right

### ISSUE THREAD

**Issue by Kriknav** [r00telement/SmartHunter#3]
I was trying to use the Monster Part/Status options for ShowUnchanged: true and it didn't seem to always work. I looked at the code and I think I have a patch that might help fix the logic and also add some logic for a new option that always shows parts/statuses once they've changed from their initial value:

https://gist.github.com/Kriknav/3a34926fbbe1c0d31e40066bf67770c1

**Comment by r00telement** [comment]
ShowUnchangedParts works in tandem with HidePartsAfterSeconds. So if you enable it when the quest starts and HidePartsAfterSeconds is 20, you'll see the unchanged parts for 20 seconds. It's useful for getting an early glimpse at what parts a monster has.

You can force all parts to always be shown by setting ShowUnchangedParts to true and HidePartsAfterSeconds to some large number. It's not ideal, but it reduces the overhead of having another config setting which might confuse matters more.
