### ISSUE TITLE
Set origin/pivot of the monster bars to be the center

### ISSUE THREAD

**Issue by yuiidev** [r00telement/SmartHunter#7]
Right now when there's multiple monsters, the bars will continue being added to the right. It would be great if the origin/pivot of the widget would be centered. This way the widget will take up the same amount of space on each side of the screen instead of only growing towards the right.

**Comment by r00telement** [comment]
You can achieve this a small skin change, by setting a MinWidth on the Grid inside the DataTemplate for MonsterWidgetContext, and then setting HorizontalAlignment="Center" on the ItemsControl.
